application: your-app-id
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: ssl
  version: latest

handlers:
- url: /days-left-bot
  script: main.application
  login: admin

- url: /.*
  script: main.application
