application: your-app-id
version: 5
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: ssl
  version: latest

env_variables:
  PYTHONHTTPSVERIFY: 1

handlers:
- url: /days-left-bot
  script: main.application
  login: admin

- url: /darwin-bot
  script: main.application
  login: admin

- url: /.*
  script: main.application
